### ISSUE TITLE
Connect Exercises To Database

### ISSUE THREAD

**Issue by LoickMarion** [JianmingLinUMass/ms02#40]
We need to connect the exercises to the database. Here are some starter ideas:

- Develop framework to pull questions from database
- Store exercise results in database
-  Maybe have an exercise page that allows user to practice problems they get wrong/get wrong more often?

Tentative point value: 4

**Comment by calderm** [comment]
Completed this feature, there were a number of issues working with the databases that I have now fixed, and with the other improvements I made I feel this was closer to 5 points, although perhaps only 4 of backend exclusive work.

**Comment by calderm** [comment]
Reopened to add comments for my code, now closing issue again.
