### ISSUE TITLE
Login Page Functionality

### ISSUE THREAD

**Issue by LoickMarion** [JianmingLinUMass/ms02#43]
Implement login page functionality, making sure that passwords are securely encrypted/secured. Bring user to home page on login.

Tentative points: 5

**Comment by lawrencexmeng** [comment]
Should also implement sign up functionality possibly reset password page.

**Comment by lawrencexmeng** [comment]
Completed implementation of sign up, login, and integrated as first page visited when loading website. Successfully directs users to home page. Added password encryption to SQLite database using bcyrpt.
