### ISSUE TITLE
Add Homepage Database features

### ISSUE THREAD

**Issue by LoickMarion** [JianmingLinUMass/ms02#44]
We need to add some features to the homepage that utilize the database. Here are some ideas but feel free to brainstorm more.

- Calendar that shows past activity
- Allow for future planning on said calendar
- Personalized recommendations for practice based on user data, i.e tell them to practice things they either get wrong or haven't done in a while, etc
- Connect the progress bar at the bottom to actual user progress
- Show daily streak

Tentative Points: 5

**Comment by CyberKraft** [comment]
Working on this
