### ISSUE TITLE
Add Functionality for other Languages

### ISSUE THREAD

**Issue by LoickMarion** [JianmingLinUMass/ms02#49]
After other changes, adjust web app to be functional with multiple languages.

Tentative Points: 4

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the home page to include language selection and updated content to support multiple languages.

You can review changes in this commit: https://github.com/jjyutm4532/JianmingLinUMass-ms02-49/commit/f3948885fb8cb9b1e832aa9aaf80fd7ed1ea500c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by LoickMarion** [comment]
not enough of webapp is done to implement this by deadline
